### ISSUE TITLE
Add keywords when adding a resource from the website

### ISSUE THREAD

**Issue by absorpheus** [azayneeva/FAC-Share#5]
User story:

- I can add keywords to the resource I am adding to the site 

Acceptance criteria: 

- [ ] I can see a keywords input field when submitting a resource
- [ ] When typing out a keyword I can see a dropdown list of suggestions
- [ ] When I click on a suggestion it will autocomplete the keyword
- [ ] I can add new keywords that are not in the list of suggestions

**Comment by azayneeva** [comment]
As an option: autocomplete plugin: https://stackoverflow.com/questions/19157249/autocomplete-without-jquery-ui,
[this is the source article](https://www.devbridge.com/sourcery/components/jquery-autocomplete/)
